/**
 * Flutter build configuration loader.
 *
 * Config is generated by build_web_previews.sh during build.
 * This eliminates the need to manually sync engineRevision after Flutter upgrades.
 */

export interface FlutterBuildConfig {
  engineRevision: string;
  builds: Array<{
    compileTarget: string;
    renderer: string;
    mainJsPath: string;
  }>;
}

let cachedConfig: FlutterBuildConfig | null = null;

/**
 * Fallback config matching Flutter 3.38.1.
 * Used when flutter-build-config.json cannot be loaded (e.g., local dev without build).
 */
const FALLBACK_CONFIG: FlutterBuildConfig = {
  engineRevision: "78fc3012e45889657f72359b005af7beac47ba3d",
  builds: [
    { compileTarget: "dart2js", renderer: "canvaskit", mainJsPath: "main.dart.js" },
  ],
};

/**
 * Load Flutter build configuration.
 *
 * Fetches config from /previews/flutter-build-config.json (generated during build).
 * Falls back to hard-coded values for backwards compatibility during local dev.
 *
 * @param basePath - Base path for previews (default: "/previews")
 */
export async function getFlutterBuildConfig(
  basePath: string = "/previews"
): Promise<FlutterBuildConfig> {
  if (cachedConfig) return cachedConfig;

  try {
    const response = await fetch(`${basePath}/flutter-build-config.json`);
    if (!response.ok) {
      throw new Error(`Failed to load config: ${response.status}`);
    }
    cachedConfig = await response.json();
    return cachedConfig!;
  } catch (error) {
    console.warn(
      "Failed to load Flutter build config, using fallback:",
      error instanceof Error ? error.message : error
    );
    // Return fallback but don't cache it - allow retry on next call
    return FALLBACK_CONFIG;
  }
}

/**
 * Reset cached config. For testing only.
 */
export function __resetConfigCache_TESTING_ONLY(): void {
  cachedConfig = null;
}
