export default {
    accordion: 'Accordion',
    avatar: 'Avatar',
    badge: 'Badge',
    button: 'Button',
    callout: 'Callout',
    card: 'Card',
    checkbox: 'Checkbox',
    divider: 'Divider',
    icon_button: 'IconButton',
    menu: 'Menu',
    progress: 'Progress',
    radio: 'Radio',
    select: 'Select',
    slider: 'Slider',
    spinner: 'Spinner',
    switch: 'Switch',
    tabs: 'Tabs',
    textfield: 'TextField',
    tooltip: 'Tooltip',
}
