export default {
  accordion: 'Accordion',
  avatar: 'Avatar',
  badge: 'Badge',
  button: 'Button',
  callout: 'Callout',
  card: 'Card',
  checkbox: 'Checkbox',
  dialog: 'Dialog',
  divider: 'Divider',
  icon_button: 'IconButton',
  menu: 'Menu',
  popover: 'Popover',
  progress: 'Progress',
  radio: 'Radio',
  select: 'Select',
  slider: 'Slider',
  spinner: 'Spinner',
  switch: 'Switch',
  tabs: 'Tabs',
  textfield: 'TextField',
  toggle: 'Toggle',
  toggle_group: 'Toggle Group',
  tooltip: 'Tooltip',
}
